### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by Fastidious** [dtonon/oracolo#4]
If a long note has a link, say `https://example.com` it will render plain, without linking it. Can it be made, so links are actually linked?

**Comment by Fastidious** [comment]
I noticed that `---` aren't being rendered as "—" either (and I sure `--` is in the same situation)[1]. It would be nice to have curly quotes too (which njump.me renders nicely).

[1] See:
https://ferengi.one/i/#3ac8b3dbbebc5203c696f1852eb2e64de21b8c87d6ce5fb95157e602682a8ec6
https://njump.me/nevent1qqsr4j9nmwltc5src6t0rpfwktnymcsm3jradnjlh9g40eszdq4ga3szypy2z0hr26xxnne0wtvwlhuss8clrqz9w4ssmmdgtzl485et8yr5cx0squ8

**Comment by dtonon** [comment]
Fixed.

> I noticed that --- aren't being rendered as "—" ...

Please open a different issue.

**Comment by Fastidious** [comment]
Were the links addressed on this issue? I just pulled and I still see https://... unlinked.

**Comment by dtonon** [comment]
Can you share a nevent?

**Comment by Fastidious** [comment]
Sure, this one: https://njump.me/nevent1qqsvh4mztkxus2pnnfhkw07y23yt8rd8mtpcx5u0sl45wxa08xj3r2qzypy2z0hr26xxnne0wtvwlhuss8clrqz9w4ssmmdgtzl485et8yr5clj5c9g

It shows fine on njump.me, but not on Oracolo.

**Comment by dtonon** [comment]
Thanks. The problem is related to the final parenthesis, and the link is broken on Njump, too. I will investigate.

**Comment by Fastidious** [comment]
This is still broken. See: https://ferengi.one/i/#cbd7625d8dc828339a6f673fc45448b38da7dac383538f87eb471baf39a511a8
